language: php
php:
    - "5.4"
    - "5.5"
    - "5.6"
    - "7.0"
    - "7.1"
    - "nightly"
    - hhvm
sudo: false
dist: trusty
before_script: rm composer.lock && composer install
script: ./vendor/phpunit/phpunit/phpunit
